config/routes.rb
Rails.application.routes.draw do  
 
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords" }

  get 'welcome/index'
  
  get 'welcome/contact'

  get 'appointments/index'

  get 'appointments/new'

  get 'appointments/show'

  get 'appointments/edit'

  get 'users/index'

  get 'users/show'

  resources :appointments
  resources :users
  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	set_meta_tags title: 'Test Title',
              	  description: 'Mere Image Salon.',
              	  keywords: 'Site, Login, Members'
  end

  def contact
        set_meta_tags title: 'Contact Us',
                  description: 'Mere Image Salon contact page.',
                  keywords: 'Site, Login, Members'
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/contact.html.erb
<div class="row">
<div class="large-12 columns">

<h1>Contact Us</h1>

</div>
</div>

<div class="row">
  <div class="large-12 columns">
    <h3>Give us a call: <small> 515 - 955 - 2241</small></h3>
  </div>
  <div class="large-12 columns">
    <div class="flex-video">
      <iframe width="600" height="450" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJQwfQaxR28ocR7aQ-IaKjvxg&key=<%=ENV['GOOGLE_MAPS_KEY'] %>" allowfullscreen></iframe>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
       
      <div class="row">
        <div class="small-12 medium-12 large-12 columns">
        <div class="slider">
          <div><%= image_tag "mis_stock_images/car-wind.jpg" %></div>
          <div><%= image_tag "mis_stock_images/urban-leeroy.jpg" %></div>
          <div><%= image_tag "mis_stock_images/woman-juliacaesar.jpg" %></div>
        </div>
        
        <hr/>
        </div>
      </div>
      
     
     
      <div class="row">
        <div class="medium-4 large-4 columns">
          <%= image_tag "mis_stock_images/szolkin.jpg" %>
          <h4>This is a content section.</h4>
          <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
        </div>
        
        <div class="medium-4 large-4 columns">
          <%= image_tag "mis_stock_images/urban-leeroy.jpg" %>          
          <h4>This is a content section.</h4>
          <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
        </div>
        
        <div class="medium-4 large-4 columns">
          <%= image_tag "mis_stock_images/woman-juliacaesar.jpg" %>
          <h4>This is a content section.</h4>
          <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
        </div>
      
        </div>
        
     
    <div class="row">
        <div class="large-12 columns">
        
          <div class="panel">
            <h4>Get in touch!</h4>
                
            <div class="row">
              <div class="large-9 columns">
                <p>We'd love to hear from you, you attractive person you.</p>
              </div>
              <div class="large-3 columns">
                <%= link_to "Contact Us", welcome_contact_path, class: "radius button right" %>
              </div>
            </div>
          </div>
          
        </div>
      </div>
     
       
      