config/routes.rb
Rails.application.routes.draw do  
 
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords" }

  get 'welcome/index'
  
  get 'welcome/contact'

  get 'appointments/index'

  get 'appointments/new'

  get 'appointments/show'

  get 'appointments/edit'

  get 'users/index'

  get 'users/show'

  resources :appointments
  resources :users
  root 'welcome#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	belongs_to :user
	belongs_to :specialist
	
	validates :appointment_type, presence: true
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!
  before_filter :find_appointment, :only => [:edit, :update, :show, :destroy]
  
  def index
  	set_meta_tags title: 'Appointments Page',
                  description: 'Account managers can view and specialists can view all open and scheduled appointments here.',
                  noindex: true
	if current_user.is_customer?
		redirect_to current_user
	else
  		@appointments = Appointment.all
	end
  end

  def new
	if current_user.is_customer?
		redirect_to current_user
	else
  		@appointment = Appointment.new
	end
  end

  def create
  	@appointment = Appointment.new(appointment_params)
    	@appointment.user = current_user  	
    	if @appointment.save
  		redirect_to @appointment
  	else
  		render 'new'
  	end
  end

  def edit
	if current_user.is_customer?
		redirect_to current_user 
	end
  end

  def update
    if @appointment.update(appointment_params)
      redirect_to @appointment
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
  	@appointment.destroy
  	redirect_to root_path
  end

  private
  	def appointment_params
  		params.require(:appointment).permit(:appointment_type)
  	end

  private
    def find_appointment
      @appointment = Appointment.find(params[:id])
    end

end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<% if @appointment.errors.any? %>
  <div class="row">
    <div class="large-12 columns">
      <div data-alert class="alert-box alert radius">
        <h4>
          <%= pluralize(@appointment.errors.count, "error") %> must be corrected to schedule this appointment:
        </h4>
        <ul>
          <% @appointment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

<%= form_for @appointment do |f| %>

  <div class="row">
    <div class="large-12 large-centered columns">
      <%= f.label :appointment_type %><br>
      <%= f.select :appointment_type, 
        Service.all.map { |service| [service.name, service.id] },
                        { include_blank: true }, 
                        {class: 'chosen-select'} %>
      <br>
    </div>

    <div class="large-12 large-centered columns">
      <%= f.submit "Submit", :class => "medium button success" %>
    </div>
  </div>
<% end %>

<script>
  jQuery('#datetimepicker').datetimepicker({
    format:'D M Y h:m a',
    formatTime:'h:m a',
  });
</script>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<div class="row">
  <% @appointments.each do |appointment| %>
    <div class="small-12 medium-4 large-3">
        <ul class="pricing-table">
          <li class="title">Appointment @ <%= appointment.appointment_time %></li>
          <li class="description">
            Your appointment is with <%= appointment.admin.first_name %>
          </li>
          <li class="bullet-item">
            You are scheduled for a(n) <%= appointment.appointment_type %>
          </li>
          <ul class="stack button-group">
            <li class="cta-button">
              <%= link_to 'View', appointment_path(appointment), class: 'button info' %>
            </li>
            <li class="cta-button">
              <%= link_to 'Edit', edit_appointment_path(appointment), class: 'button success' %>
            </li>
            <li class="cta-button">
              <%= link_to 'Cancel', appointment_path(appointment), class: 'button alert',
                method: :delete,
                data: { confirm: 'Are you sure you want to cancel this appointment?' } %>
            </li>
          </ul>
        </ul>
    </div>
  <% end %>
</div>

app/views/appointments/new.html.erb
<h1> New Appointment</h1>

<%= render 'form' %>
 
<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<%= @appointment.appointment_time %>
<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>